/**
 * Smart Warehouse System — Shared Constants
 *
 * Centralized configuration values, stage definitions, and lookup tables
 * used across the application. Keeping constants in one place ensures
 * consistency and makes future changes safer.
 *
 * @module constants
 */

/**
 * Ordered fulfillment pipeline stages. An order progresses through
 * these stages from left to right during its lifecycle.
 * @type {ReadonlyArray<string>}
 */
export const STAGE_FLOW = Object.freeze([
  'Created',
  'Allocated',
  'Picking',
  'Packing',
  'QC',
  'Dispatched',
]);

/**
 * Available priority tiers with their scoring weights used by the
 * allocation engine to rank orders.
 * @type {Readonly<Record<string, number>>}
 */
export const PRIORITY_WEIGHTS = Object.freeze({
  Urgent: 100,
  Standard: 50,
  Low: 10,
});

/** @type {ReadonlyArray<string>} */
export const PRIORITY_TIERS = Object.freeze(Object.keys(PRIORITY_WEIGHTS));

/**
 * Deadline proximity thresholds (in hours) and their corresponding
 * bonus scores added to priority calculations.
 * @type {ReadonlyArray<{maxHours: number, bonus: number}>}
 */
export const DEADLINE_BONUSES = Object.freeze([
  { maxHours: 2, bonus: 40 },
  { maxHours: 6, bonus: 20 },
]);

/**
 * Maximum bonus points an order can receive from its age in the queue.
 * Prevents very old, low-priority orders from dominating the queue.
 * @type {number}
 */
export const MAX_AGE_BONUS = 50;

/**
 * Multiplier applied to the number of hours an order has been waiting.
 * @type {number}
 */
export const AGE_BONUS_MULTIPLIER = 10;

/**
 * Sample Indian logistics company names used when the live simulation
 * engine generates synthetic orders.
 * @type {ReadonlyArray<string>}
 */
export const SAMPLE_CUSTOMERS = Object.freeze([
  'Delhivery Express Logistics',
  'Flipkart Fulfillment Hub',
  'Amazon India Direct',
  'Tata Logistics Network',
  'Reliance Retail Supply',
  'Blue Dart Express',
  'Shadowfax Parcel Post',
  'Ecom Express Cargo',
  'Mahindra Logistics Center',
  'Xpressbees Freight',
]);

/**
 * Default deadline offsets (hours from order creation) per priority tier.
 * @type {Readonly<Record<string, number>>}
 */
export const DEFAULT_DEADLINE_HOURS = Object.freeze({
  Urgent: 2,
  Standard: 6,
  Low: 24,
});

/**
 * Kanban column configuration for the fulfillment board UI.
 * @type {ReadonlyArray<{id: string, title: string, color: string, border: string, bg: string, badgeBg: string}>}
 */
export const KANBAN_COLUMNS = Object.freeze([
  { id: 'Allocated', title: 'Allocated', color: 'blue', border: 'border-blue-200', bg: 'bg-blue-50/50', badgeBg: 'bg-blue-100 text-blue-800' },
  { id: 'Picking', title: 'Picking', color: 'amber', border: 'border-amber-200', bg: 'bg-amber-50/50', badgeBg: 'bg-amber-100 text-amber-800' },
  { id: 'Packing', title: 'Packing', color: 'orange', border: 'border-orange-200', bg: 'bg-orange-50/50', badgeBg: 'bg-orange-100 text-orange-800' },
  { id: 'QC', title: 'QC (Quality Check)', color: 'purple', border: 'border-purple-200', bg: 'bg-purple-50/50', badgeBg: 'bg-purple-100 text-purple-800' },
  { id: 'Dispatched', title: 'Dispatched', color: 'emerald', border: 'border-emerald-200', bg: 'bg-emerald-50/50', badgeBg: 'bg-emerald-100 text-emerald-800' },
]);

/**
 * Color mapping for fulfillment stages used in analytics charts.
 * @type {Readonly<Record<string, string>>}
 */
export const STAGE_COLORS = Object.freeze({
  Created: '#64748b',
  Allocated: '#3b82f6',
  Picking: '#f59e0b',
  Packing: '#ea580c',
  QC: '#9333ea',
  Dispatched: '#10b981',
});

/**
 * Color mapping for priority tiers used in analytics charts.
 * @type {Readonly<Record<string, string>>}
 */
export const PRIORITY_COLORS = Object.freeze({
  Urgent: '#ef4444',
  Standard: '#3b82f6',
  Low: '#64748b',
});

/**
 * Maximum number of orders stored in Redis or in-memory fallback.
 * @type {number}
 */
export const MAX_STORED_ORDERS = 100;

/**
 * Maximum number of orders fetched from Redis per poll.
 * @type {number}
 */
export const MAX_FETCHED_ORDERS = 50;

/**
 * E-commerce sync polling interval in milliseconds.
 * @type {number}
 */
export const ECOMMERCE_SYNC_INTERVAL_MS = 3000;

/**
 * Live simulation interval in milliseconds.
 * @type {number}
 */
export const SIMULATION_INTERVAL_MS = 15000;

/**
 * Maximum orders generated by a single simulation session.
 * @type {number}
 */
export const MAX_SIMULATION_ORDERS = 15;

/**
 * Exception probability when an order enters the Picking stage (0–1).
 * @type {number}
 */
export const PICKING_EXCEPTION_PROBABILITY = 0.10;

/**
 * Redis key used for storing live e-commerce orders.
 * @type {string}
 */
export const REDIS_KEY = 'live_ecommerce_orders';
